# ==========================================
# 1. UYGULAMA BİLGİSİ
# ==========================================
spring.application.name=proje-ve-gorev-yonetimi
server.port=8080

# ==========================================
# 2. H2 VERİTABANI AYARLARI (KALICI MOD)
# ==========================================
# Verileri proje içindeki "data" klasörüne kaydeder
spring.datasource.url=jdbc:h2:file:./data/pgyp_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ==========================================
# 3. TABLO VE JPA AYARLARI
# ==========================================
# Veriler varken tabloları silmez, sadece günceller
spring.jpa.hibernate.ddl-auto=update
spring.datasource.generate-unique-name=false
spring.jpa.open-in-view=false

# ==========================================
# 4. H2 KONSOLU AYARLARI
# ==========================================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# ==========================================
# 5. DİĞER AYARLAR
# ==========================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true