# ==========================================
# 1. UYGULAMA BİLGİSİ
# ==========================================
spring.application.name=proje-ve-gorev-yonetimi
server.port=8080

# ==========================================
# 2. AIVEN CLOUD MYSQL VERİTABANI AYARLARI
# ==========================================
# Aiven Host ve Port bilgileri ile URL
spring.datasource.url=jdbc:mysql://mysql-2216c6d4-pgypdb.k.aivencloud.com:22168/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_g9LT3xPFOT1mMS7caZ_
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# 3. TABLO VE JPA AYARLARI
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Java sınıflarından tabloları otomatik oluşturur/günceller
spring.jpa.hibernate.ddl-auto=update
spring.datasource.generate-unique-name=false
# Hibernate'in View içinde sorgu yapmasını engeller (Performans için)
spring.jpa.open-in-view=false

# ==========================================
# 4. LOGLAMA VE SQL İZLEME
# ==========================================
# Çalışan SQL sorgularını terminalde gösterir
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true